### ISSUE TITLE
Need Improvement

### ISSUE THREAD

**Issue by fakhryalterra** [group-01-airbnb-project/airbnb-api#43]
https://github.com/group-01-airbnb-project/airbnb-api/blob/aab4b58383d2cb81c1a686f57c1d4e6cf98c16c6/features/user/controller/user_controller.go#L36-L44

@wayanputri @pradanadp guys minta tolong untuk pengecekan error seperti ini lebih diperhatikan lagi

Coba diperhatikan, jika ada error, maka akan masuk ke block `if err!=nil`. 
Namun ketika ternyata pesan errornya tidak termasuk di kriteria pengecekan `strings.Contains` yang sudah kalian define maka dia akan masuk kemana?
padahal disana tidak ada else atau kondisi error defaultnya.
Jika 3 if tersebut tidak ada yang terpenuhi. maka eksekusi program akan dilanjutkan ke line bawahnya lagi. Ini akan menyebabkan flow codingan yang seharusya return error jadi return success.

**Comment by wayanputri** [comment]
oalah, iya mas
